PORT_DISPATCHER_CLIENT_STORAGE = 6000
POOL_CSM_PORT = 7000
POOL_FN_PORT = 8000

f = 7

PORT_DISPATCHER_CLIENT_STORAGE = PORT_DISPATCHER_CLIENT_STORAGE + f
POOL_CSM_PORT = POOL_CSM_PORT + f
POOL_FN_PORT = POOL_FN_PORT + f